import {useEffect,useState} from 'react';

type Props={room:any;busy:boolean;act:(action:string,args?:Record<string,unknown>)=>void;ask:(action:string,title:string,body:string,args?:Record<string,unknown>)=>void};
export default function SheriffControls({room:r,busy,act,ask}:Props){
 const [target,setTarget]=useState('');
 useEffect(()=>setTarget(''),[r.epoch]);
 if(!['sheriffSignup','sheriffSpeech','sheriffVote','badge','order'].includes(r.phase))return null;
 const me=r.me,s=r.sheriff,person=(id:string)=>r.players.find((p:any)=>p.id===id),label=(id:string)=>person(id)?person(id).seat+' 号 '+person(id).name:'无人';
 const choices=(players:any[],passLabel:string)=><div className="choice-grid">{players.map(p=><button type="button" key={p.id} className={'choice '+(target===p.id?'selected':'')} disabled={busy} aria-pressed={target===p.id} onClick={()=>setTarget(p.id)}><b>{String(p.seat).padStart(2,'0')}</b><span>{p.name}</span></button>)}<button type="button" className={'choice pass '+(target==='pass'?'selected':'')} disabled={busy} aria-pressed={target==='pass'} onClick={()=>setTarget('pass')}>{passLabel}</button></div>;
 return <section className="sheriff-controls">
  {r.phase==='sheriffSignup'&&(r.host?<p className="muted">已收到 {s.signupCount} / {r.size} 位玩家的报名选择。先竞选警长，暂不公布昨夜死亡。</p>:<><p className="muted">请选择是否竞选警长。结束报名前可以修改；上警后再退水，也不能投警长票。</p><div className="button-row"><button type="button" className={s.mySignup===true?'primary':'secondary'} disabled={busy} onClick={()=>act('sheriffSignup',{run:true})}>我要上警</button><button type="button" className={s.mySignup===false?'primary':'secondary'} disabled={busy} onClick={()=>act('sheriffSignup',{run:false})}>不上警</button></div><p className="muted small">{s.mySignup===null?'尚未选择':s.mySignup?'已选择上警':'已选择不上警'}</p></>)}
  {r.phase==='sheriffSpeech'&&<><p className="muted small">{s.round===2?'警长平票 PK':'竞选者'}：{s.active.map(label).join('、')||'无人'}。{s.round===2?'PK 阶段不能退水。':'退水后仍无警长投票权。'}</p>{!r.host&&<p className="muted">{r.speaker?label(r.speaker)+' 正在发言。':'等待法官结束竞选发言。'}{r.speaker===me?.id?'现在轮到你，发言在语音房进行。':''}</p>}{s.round===1&&s.active.includes(me?.id)&&<button type="button" className="secondary full" disabled={busy} onClick={()=>ask('withdraw','确认退水？','退出本轮警长竞选，不能重新加入，也不能投警长票。')}>退出警长竞选</button>}</>}
  {r.phase==='sheriffVote'&&<><p className="muted small">已收到 {s.voteCount} / {s.voteTotal} 张警长票。候选人：{s.active.map(label).join('、')}。</p>{!r.host&&(s.myVote?<p className="success">已选择 {s.myVote==='pass'?'弃票':label(s.myVote)}，等待法官计票。</p>:!s.canVote?<p className="muted">你最初上了警，本轮不能投警长票；退水或 PK 落选不会恢复此投票权。</p>:<>{choices(r.players.filter((p:any)=>s.active.includes(p.id)),'警长票弃票')}<button type="button" className="primary full" disabled={busy||!target} onClick={()=>ask('sheriffVote','确认警长票？','提交后不能修改。'+(target==='pass'?'本轮弃票。':'投给 '+label(target)),{target})}>提交警长票</button></>)}</>}
  {r.phase==='badge'&&<><p className="muted">{label(r.badgeFrom)} 请移交警徽给尚未翻牌的存活玩家，或撕毁警徽。{r.host?'法官仅在原警长明确选择或离线时代操作。':''}</p>{(r.host||me?.id===r.badgeFrom)&&<>{choices(r.players.filter((p:any)=>p.alive&&!p.idiotRevealed&&p.id!==r.badgeFrom),'撕毁警徽')}<button type="button" className="primary full" disabled={busy||!target} onClick={()=>ask('badge','确认警徽处理？',target==='pass'?'撕毁后本局不再有警长。':'移交警徽给 '+label(target),{target})}>确认警徽处理</button></>}</>}
  {r.phase==='order'&&<><p className="muted">{label(r.sheriffId)} 是警长。请选择座位号码方向，从警长相邻的存活玩家开始，警长最后归票。{r.host?'可在警长语音确认后代操作。':''}</p>{(r.host||me?.id===r.sheriffId)&&<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>ask('speechOrder','按号码递增发言？','沿号码递增方向，警长最后发言。',{direction:'ascending'})}>号码递增 →</button><button type="button" className="secondary" disabled={busy} onClick={()=>ask('speechOrder','按号码递减发言？','沿号码递减方向，警长最后发言。',{direction:'descending'})}>← 号码递减</button></div>}</>}
 </section>;
}
