"use client";
import {useState,useEffect,useRef} from 'react';
import {Moon,Sun,ArrowUpRight,ArrowRight,Headphones,Users,Shield,Link as LinkIcon,Copy,Check,Eye,Mic,Clock,BookOpen,RotateCcw,LogOut,Volume2} from 'lucide-react';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {ROLES,ROLE_HELP,PHASES,PLAYER_SIZES,recommendedConfig,configurationError,victoryText,witchText,type GameConfig} from '@/lib/rules';
import SetupEditor,{SetupSummary} from './setup-editor';

const script:Record<string,string>={
 lobby:'请大家打开邀请链接，使用语音房昵称入座，确认规则后点击准备。',
 deal:'请各位查看自己的身份，记住后收好，不要向他人展示。确认后我们进入第一夜。',
 guard:'天黑请闭眼。守卫请睁眼，选择守护目标或空守；不能连续两夜守同一人。',
 wolves:'上一位行动结束，请闭眼。狼人请睁眼，在网页上选择袭击目标。请勿在公共语音房讨论。',
 seer:'狼人请闭眼。预言家请睁眼，请在网页上查验一位玩家。',
 witch:'预言家请闭眼。女巫请睁眼，请在网页上决定是否使用药水。',
 dawn:'女巫请闭眼。天亮了，所有人睁眼。确认后公布昨夜出局情况。',
 speech:'请按座位顺序发言，其他玩家先关闭麦克风。发言结束后交给下一位。',
 vote:'请各位在网页上投票。未提交前互相不可见，结束后公布票数。',
 hunter:'猎人请决定是否开枪；操作完成后继续游戏。',
 dusk:'本轮放逐已结束。请所有存活玩家准备进入下一夜。',
 ended:'本局结束，现在可以公开身份，聊聊刚刚发生了什么。'
};
const advanceLabel:Record<string,string>={guard:'结束守护阶段',deal:'进入第一夜',wolves:'结束狼队行动',seer:'结束查验阶段',witch:'结束用药阶段',dawn:'公布天亮结果',speech:'开始放逐投票',vote:'结束投票并计票',dusk:'进入下一夜'};
type Confirm={title:string;body:string;action:string;args?:Record<string,unknown>;epoch:number};
export default function TableApp(){
 const [r,setR]=useState<any>(null),[id,setId]=useState(''),[name,setName]=useState(''),[size,setSize]=useState('9'),[voice,setVoice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[rules,setRules]=useState(false),[identity,setIdentity]=useState(false),[showRoles,setShowRoles]=useState(false),[target,setTarget]=useState(''),[kind,setKind]=useState('pass'),[confirm,setConfirm]=useState<Confirm|null>(null),[now,setNow]=useState(Date.now()),[synced,setSynced]=useState(0),[invite,setInvite]=useState('');
 const [setup,setSetup]=useState<GameConfig>(recommendedConfig(9)),[editSetup,setEditSetup]=useState<GameConfig|null>(null),[editEpoch,setEditEpoch]=useState(0);
 function changeSize(value:string){setSize(value);setSetup(previous=>previous.mode==='recommended'?recommendedConfig(Number(value),previous.preset):{...previous,roles:recommendedConfig(Number(value),previous.preset).roles});}
 const active=useRef(false),seq=useRef(0),roomRef=useRef<any>(null);roomRef.current=r;
 useEffect(()=>{const room=new URLSearchParams(location.search).get('room')||'';setId(room);setLoaded(true);},[]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);const hide=()=>{if(document.hidden){setIdentity(false);setShowRoles(false);}};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hide);}},[]);
 useEffect(()=>{setTarget('');setKind('pass');},[r?.epoch]);
 async function refresh(roomId=id){if(!roomId||active.current)return;const q=++seq.current;try{const res=await fetch('/api/room?id='+encodeURIComponent(roomId),{cache:'no-store'});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'房间加载失败');if(q===seq.current){setR(data);setError('');setSynced(Date.now());}}catch(e){if(q===seq.current)setError(e instanceof Error?e.message:'连接中断，请重试');}}
 useEffect(()=>{if(!id)return;const poll=()=>{if(!document.hidden)void refresh(id);};poll();const timer=setInterval(poll,2500);document.addEventListener('visibilitychange',poll);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',poll);};},[id]);
 async function send(action:string,args:Record<string,unknown>={}){
  if(active.current)throw new Error('操作进行中，请稍候');active.current=true;setBusy(true);const q=++seq.current;
  try{const current=roomRef.current;const res=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:current?.id||id,epoch:current?.epoch,...args})});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'操作失败');if(q===seq.current){setR(data);setError('');setSynced(Date.now());}if(action==='create'){history.replaceState(null,'','/?room='+data.id);setId(data.id);}if(action==='leave'){setR(null);setId('');history.replaceState(null,'','/');}return data;
  }catch(e){const message=e instanceof Error?e.message:'连接中断，请重试';setError(message);throw e;}finally{active.current=false;setBusy(false);}
 }
 function act(action:string,args:Record<string,unknown>={}){void send(action,args).catch(()=>{});}
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools=[{name:'read_werewolf_room',title:'读取当前房间',description:'读取当前页面允许该席位看到的房间状态；不披露任何额外身份。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('不接受额外参数');const v=roomRef.current;if(!v)throw new Error('尚未进入房间');return {roomId:v.id,phase:v.phase,day:v.day,mySeat:v.me?.seat||null,message:v.message};}},
  {name:'set_werewolf_ready',title:'设置准备状态',description:'为当前浏览器中已入座的玩家设置准备状态，只能在等待入座阶段操作。',inputSchema:{type:'object',properties:{ready:{type:'boolean'}},required:['ready'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||typeof input.ready!=='boolean'||Object.keys(input).some(k=>k!=='ready'))throw new Error('ready 必须是布尔值');const v=roomRef.current;if(!v?.me||v.phase!=='lobby')throw new Error('需要在等候中的房间入座');const next=await send('ready',{id:v.id,epoch:v.epoch,ready:input.ready});return {seat:next.me.seat,ready:next.me.ready};}}];
  for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();
 },[]);
 async function share(){const link=location.origin+'/?room='+r.id;setInvite(link);try{await navigator.clipboard.writeText(link);toast.success('邀请链接已复制，发给朋友就能入座');}catch{toast.info('请复制下方邀请链接');}}
 function ask(action:string,title:string,body:string,args:Record<string,unknown>={}){setConfirm({action,title,body,args,epoch:r.epoch});}
 function advance(){
  let missing=0;
  if(r.phase==='guard')missing=r.players.some((p:any)=>p.alive&&p.role==='guard')&&!r.hostNight.guardDone?1:0;
  if(r.phase==='wolves')missing=r.players.filter((p:any)=>p.alive&&p.role==='wolf'&&!r.wolfVotes[p.id]).length;
  if(r.phase==='seer')missing=r.players.some((p:any)=>p.alive&&p.role==='seer')&&!r.hostNight.seerDone?1:0;
  if(r.phase==='witch')missing=r.players.some((p:any)=>p.alive&&p.role==='witch')&&!r.hostNight.witch?1:0;
  if(r.phase==='vote')missing=r.voteTotal-r.voteCount;
  if(missing)ask('advance','还有 '+missing+' 位尚未操作','提前结束会把尚未提交的行动视为放弃。确认语音房里的玩家已经完成后再继续。');
  else if(r.phase==='speech'&&!r.lastSpeaker)ask('advance','提前结束发言？','还有玩家没有轮到。确认大家已经说完，再开始投票。');
  else act('advance');
 }
 const isRoom=r&&r.phase!=='join',me=r?.me,players:any[]=r?.players||[],night=['night','guard','wolves','seer','witch','dawn'].includes(r?.phase);
 const person=(pid:string)=>players.find(p=>p.id===pid);
 const label=(pid:string)=>pid==='pass'?'放弃':person(pid)?person(pid).seat+' 号 '+person(pid).name:'无人';
 const speaker=person(r?.speaker),seconds=r?.deadline?Math.max(0,Math.ceil((r.deadline-now)/1000)):90;
 const currentSetup:GameConfig=r?.setup||setup,setupInvalid=configurationError(Number(size),setup);
 const submitted=r?.submitted;
 let options=players.filter(p=>p.alive&&p.id!==me?.id);
 if(r?.action==='guard')options=players.filter(p=>p.alive&&p.id!==r.guardLast);
 if(r?.phase==='vote')options=options.filter(p=>!p.idiotRevealed);
 if(r?.action==='wolves')options=options.filter(p=>!r.wolfTeam.some((w:any)=>w.id===p.id));
 if(r?.phase==='vote'&&r.runoff.length)options=options.filter(p=>r.runoff.includes(p.id));
 const choice=(withPass=true)=><div className="choice-grid">{options.map(p=><button disabled={busy} aria-pressed={target===p.id} className={'choice '+(target===p.id?'selected':'')} onClick={()=>setTarget(p.id)} key={p.id}><b>{String(p.seat).padStart(2,'0')}</b><span>{p.name}</span>{target===p.id&&<Check size={16}/>}</button>)}{withPass&&<button className={'choice pass '+(target==='pass'?'selected':'')} aria-pressed={target==='pass'} onClick={()=>setTarget('pass')}>放弃本次行动</button>}</div>;
 const hostControls=<>
  <div className="host-script"><div className="section-label"><Volume2 size={15}/> 法官口播</div><p>{script[r?.phase]||''}</p></div>
  {['guard','wolves','seer','witch','dawn'].includes(r?.phase)&&<div className="private-summary"><span className="section-label"><Shield size={15}/> 仅法官可见</span>{r.phase==='guard'?<p>守卫：{r.hostNight.guardDone?'已完成 · '+label(r.hostNight.guardTarget):'未提交 / 可空守'}</p>:r.phase==='wolves'?<p>狼队已提交 {Object.keys(r.wolfVotes).length} / {players.filter(p=>p.alive&&p.role==='wolf').length}<br/>{Object.entries(r.wolfVotes).map(([pid,t])=><span key={pid}>{person(pid)?.seat} 号 → {label(t as string)}<br/></span>)}</p>:r.phase==='seer'?<p>查验：{r.hostNight.seerDone?'已完成':'等待中 / 可跳过'}{r.hostNight.checks.filter((x:any)=>x.day===r.day).map((x:any)=><span key={x.day}><br/>{x.seat} 号：{x.result}</span>)}</p>:<p>{r.setup.roles.guard>0&&<>守护：{label(r.hostNight.guardTarget)}<br/></>}狼刀：{label(r.victim)}<br/>女巫：{r.hostNight.witch?({heal:'使用解药',poison:'毒 '+label(r.hostNight.witch.target),pass:'不用药'} as any)[r.hostNight.witch.kind]:'未提交 / 可跳过'}</p>}</div>}
  {r?.phase==='lobby'&&<><button className="secondary full" disabled={busy} onClick={()=>{setEditSetup(r.setup);setEditEpoch(r.epoch);}}>修改本桌玩法</button><p className="muted small">{players.filter(p=>p.ready).length} / {r.size} 位玩家准备好了</p><button className="primary full" disabled={busy||players.length!==r.size||players.some(p=>!p.ready)} onClick={()=>act('deal')}>随机发放身份 <ArrowRight size={18}/></button></>}
  {r?.phase==='deal'&&<p className="muted small">{players.filter(p=>p.ack).length} / {r.size} 位玩家已确认身份</p>}
  {r?.phase==='speech'&&<><div className="speaker-clock"><Mic/><div><span>{speaker?.seat} 号 · {speaker?.name}</span><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b></div></div><p className="muted small">{seconds===0?'建议时间已到，法官可以交给下一位。':'每人建议 90 秒，由法官决定何时结束。'}</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>act('restartTimer')}><RotateCcw size={16}/>重置</button><button className="secondary grow" disabled={busy||r.lastSpeaker} onClick={()=>act('nextSpeaker')}>下一位发言 <ArrowRight size={16}/></button></div></>}
  {r?.phase==='vote'&&<p className="muted small">已收到 {r.voteCount} / {r.voteTotal} 张票{r.voteRound===2?' · 平票加投':''}</p>}
  {advanceLabel[r?.phase]&&<button className="primary full" disabled={busy||(r.phase==='deal'&&players.some(p=>!p.ack))} onClick={advance}>{advanceLabel[r.phase]} <ArrowRight size={18}/></button>}
  {r?.phase==='hunter'&&<><p>{label(r.hunter)} 正在决定是否开枪。</p><button className="secondary full" disabled={busy} onClick={()=>ask('shoot','代猎人选择不开枪？','仅当猎人明确放弃，或离线无法操作时使用。',{target:'pass'})}>猎人放弃开枪</button></>}
  {r?.phase==='ended'&&<button className="primary full" disabled={busy} onClick={()=>ask('rematch','原班人马，再来一局','保留席位，清空上一局身份和记录。所有人重新准备后发牌。')}>再来一局 <RotateCcw size={18}/></button>}
 </>;
 return <div className="shell"><Toaster theme="dark" position="top-center"/><header><a className="brand" href="/"><Moon size={25}/><strong>月下</strong><span>狼人杀</span></a><div className="header-actions">{isRoom&&<span className={'sync '+(now-synced>10000?'offline':'')}>{now-synced>10000?'正在重新连接':'房间已同步'}</span>}<button className="text-button" aria-label="玩法约定" onClick={()=>setRules(true)}><BookOpen size={16}/><span>玩法约定</span></button></div></header>
 {error&&<div className="error-banner" role="alert"><span>{error}</span>{id&&<button className="text-button" onClick={()=>void refresh()}>重试</button>}</div>}
 {!loaded||(id&&!r)?<main className="waiting"><Moon size={32}/><h1>正在寻找你的牌桌…</h1><p className="muted">{error?'请检查邀请链接，或重新建一桌。':'稍等，房间状态正在同步。'}</p>{error&&<a className="secondary" href="/">回到建房页</a>}</main>:!id?<main className="entry"><section className="intro"><span className="eyebrow">THE NIGHT IS YOURS</span><h1>人齐了，<br/>就开一局。</h1><p>语音里见，月下入座。<br/>发身份、走流程、计票，都交给这里。</p><div className="steps"><span><LinkIcon/> 分享房间</span><i>·</i><span><Shield/> 私密身份</span><i>·</i><span><Users/> 法官主持</span></div><div className="table-preview"><div className="table-ring"><Moon/><span>今晚，谁是狼人？</span><small>6–12 位玩家 · 另加 1 位法官</small></div>{Array.from({length:Number(size)},(_,i)=><span key={i} className="seat-orbit" style={{'--i':i,'--step':(360/Number(size))+'deg'} as React.CSSProperties}>{String(i+1).padStart(2,'0')}</span>)}</div></section><form className="create-panel" onSubmit={e=>{e.preventDefault();act('create',{name,size:Number(size),voice,setup});}}><div className="panel-top"><span className="eyebrow">NEW TABLE</span><span className="pill">法官建房</span></div><h2>开一桌</h2><p className="muted">建好房间，把邀请链接发到语音房。</p><label>怎么称呼你<input required value={name} onChange={e=>setName(e.target.value)} placeholder="法官昵称" maxLength={16}/></label><label>本局玩家人数<Select value={size} onValueChange={changeSize}><SelectTrigger className="field"><SelectValue/></SelectTrigger><SelectContent>{PLAYER_SIZES.map(n=><SelectItem key={n} value={String(n)}>{n} 人局 · 不含法官</SelectItem>)}</SelectContent></Select></label><SetupEditor size={Number(size)} setup={setup} onChange={setSetup}/><label>语音房链接 <span className="muted">选填</span><input type="url" value={voice} onChange={e=>setVoice(e.target.value)} placeholder="粘贴你们正在用的语音房链接"/></label><button className="primary" disabled={busy||!name.trim()||!!setupInvalid}>{busy?'正在建房…':'创建房间'} <ArrowUpRight size={19}/></button><div className="note"><Shield size={17}/><span>法官不占玩家席位。每个人用自己的手机入座。房间保留 24 小时。</span></div></form></main>:r?.phase==='join'?<main className="join-layout"><span className="eyebrow">YOUR SEAT IS WAITING</span><h1>{r.hostName} 的牌桌</h1><p className="muted">{r.size} 人局 · 已入座 {r.count} 人</p><SetupSummary setup={r.setup} size={r.size}/><form className="create-panel" onSubmit={e=>{e.preventDefault();act('join',{name});}}><h2>今晚，你来几号？</h2><p className="muted">入座后自动分配座位，身份在开局时随机发放。</p><label>语音房里怎么称呼你<input required maxLength={16} value={name} onChange={e=>setName(e.target.value)} placeholder="输入你的昵称"/></label><button className="primary" disabled={busy||!r.canJoin||!name.trim()}>{busy?'正在入座…':r.canJoin?'加入这一局':'已开局或座位已满'} <ArrowRight size={18}/></button><div className="note"><Shield size={17}/><span>请始终使用同一个浏览器。刷新可以恢复席位，换浏览器或清除数据会丢失席位。</span></div></form><a href="/" className="text-button">自己开一桌 <ArrowUpRight size={16}/></a></main>:isRoom?<main className="room">
 <section className="room-heading"><div><span className="eyebrow">TABLE / {r.id.slice(-6).toUpperCase()}</span><h1>{r.hostName} 的牌桌 <span>{r.size} 人局</span></h1><p className="muted small">{r.host?'你是本局法官，不参与游戏':me?me.seat+' 号 · '+me.name:''}</p></div><div className="button-row">{r.voice?<a className="secondary" href={r.voice} target="_blank" rel="noopener noreferrer"><Headphones size={17}/>语音房 <ArrowUpRight size={15}/></a>:<span className="voice-hint"><Headphones size={17}/> 语音在原来的房间继续</span>}<button className="secondary" onClick={share}><Copy size={16}/>邀请朋友</button></div></section>
 {invite&&<div className="invite-row"><label htmlFor="invite">邀请链接</label><input id="invite" readOnly value={invite} onFocus={e=>e.target.select()}/><button className="text-button" onClick={()=>setInvite('')}>收起</button></div>}
 <SetupSummary setup={r.setup} size={r.size}/><div className="game-layout"><section className="board-column"><div className={'phase-banner '+(night?'is-night':'')}><div className="phase-symbol">{night?<Moon size={28}/>:r.phase==='lobby'?<Users size={28}/>:<Sun size={28}/>}</div><div><span className="eyebrow">{r.day?'ROUND '+String(r.day).padStart(2,'0'):'WAITING FOR FRIENDS'}</span><h2>{r.phase==='ended'?r.winner+'阵营获胜':PHASES[r.phase]}</h2><p>{r.message}</p></div></div>
 <div className="board-top"><h3>玩家席位 <span>{players.length} / {r.size}</span></h3>{r.host&&r.phase!=='lobby'&&<label className="switch-label">显示身份 <Switch checked={showRoles} onCheckedChange={setShowRoles} aria-label="显示所有玩家身份"/></label>}{!r.host&&me?.role&&<button className="text-button accent" onClick={()=>setIdentity(true)}><Eye size={16}/>我的身份</button>}</div>
 <div className="seat-grid">{Array.from({length:r.size},(_,i)=>{const p=players.find(p=>p.seat===i+1);return <article key={i} className={'player-seat '+(!p?'empty-seat':'')+(p&&!p.alive?' dead-seat':'')+(p?.id===r.speaker?' speaking-seat':'')}><div className="seat-top"><span className="seat-num">{String(i+1).padStart(2,'0')}</span>{p&&<span className="player-status">{r.phase==='lobby'?(p.ready?<><Check size={13}/>已准备</>:'未准备'):!p.alive?'已出局':p.idiotRevealed?'已翻牌 · 无票':p.id===r.speaker?<><Mic size={13}/>发言中</>:'存活'}</span>}</div><div className={'avatar '+(!p?'vacant':'')}>{p?p.name.slice(0,1):<Users size={21}/>}</div><strong>{p?p.name:'等待入座'}</strong>{p&&p.id===me?.id&&<span className="you-label">你</span>}{p&&(r.phase==='ended'||showRoles||p.idiotRevealed)&&p.role&&<span className={'role-tag '+(p.role==='wolf'?'wolf':'')}>{ROLES[p.role]}</span>}{p&&r.phase==='deal'&&<small className="muted">{p.ack?'身份已确认':'正在查看身份'}</small>}{p&&r.host&&r.phase==='lobby'&&<button className="remove-seat" onClick={()=>ask('kick','移除 '+p.name+'？','仅移除这个等待中的席位，对方可以重新加入。',{target:p.id})}>移除</button>}</article>;})}</div>
 <div className="round-log"><div className="board-top"><h3>本局记录</h3><span className="muted small">只记录公开信息</span></div>{r.logs.length?<ol>{[...r.logs].reverse().map((l:any,i:number)=><li key={i}><span>{l.day?'第 '+l.day+' 轮':'准备'}</span><p>{l.text}</p></li>)}</ol>:<p className="muted small">开局后，天亮结果和投票结果会留在这里。</p>}</div></section>
 <aside className="action-panel"><div className="panel-top"><span className="eyebrow">{r.host?'HOST DESK':'YOUR TURN'}</span><span className="pill">{r.host?'法官主持台':me?.seat+' 号玩家'}</span></div><h2>{r.host?'把这一局，带好。':r.phase==='lobby'?'准备入夜。':r.action?PHASES[r.action]:r.phase==='vote'?'你的这一票':r.phase==='ended'?'好局，下次再来。':'现在轮到谁？'}</h2>
 {r.host?hostControls:<>
  {r.phase==='lobby'&&<><p className="muted">先加入你们的语音房，确认玩法后准备。全部人准备好，法官就可以发身份。</p><button className={me?.ready?'secondary full':'primary full'} disabled={busy} onClick={()=>act('ready',{ready:!me?.ready})}>{me?.ready?<><Check size={18}/>已准备 · 点击取消</>:'我准备好了'}</button><button className="text-button leave" disabled={busy} onClick={()=>act('leave')}><LogOut size={15}/>离开席位</button></>}
  {r.phase==='deal'&&<><p className="muted">只在自己的屏幕查看身份，记住后收好。</p><button className="primary full" onClick={()=>setIdentity(true)}><Eye size={18}/>查看我的身份</button><button className="secondary full" disabled={busy||me.ack} onClick={()=>act('ack')}>{me.ack?'已确认，等待开局':'我记住身份了'}</button></>}
  {r.action&&<>{r.action==='wolves'&&<p className="muted small">你的狼队：{r.wolfTeam.map((p:any)=>p.seat+' 号 '+p.name).join('、')}。票数相同则空刀。</p>}{r.action==='guard'&&<p className="muted small">可以守自己，也可以空守。{r.guardLast?'上一夜守了 '+label(r.guardLast)+'，本夜不可连守。':''} 守护不能挡毒药，同守同救仍出局。</p>}{r.action==='seer'&&<p className="muted">选择一位玩家查验。提交后，本夜不能更改。</p>}{r.action==='witch'&&<><p className="muted small">狼刀：{r.medicine.heal?label(r.victim):'解药已用完，不再显示'}<br/>解药 {r.medicine.heal?'剩 1 瓶':'已用完'} · 毒药 {r.medicine.poison?'剩 1 瓶':'已用完'}</p>{!submitted&&<label>今晚用药<Select value={kind} onValueChange={setKind}><SelectTrigger className="field"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pass">不用药</SelectItem><SelectItem value="heal" disabled={!r.medicine.heal||!r.victim||(r.victim===me.id&&!r.canSelfSave)}>使用解药（{r.canSelfSave?'首夜可以自救':'本夜不能自救'}）</SelectItem><SelectItem value="poison" disabled={!r.medicine.poison}>使用毒药</SelectItem></SelectContent></Select></label>}</>}
   {(!submitted||r.action==='wolves')&&(r.action!=='witch'||kind==='poison')&&choice(r.action!=='witch')}
   {(!submitted||r.action==='wolves')&&<button className="primary full" disabled={busy||((r.action!=='witch'||kind==='poison')&&!target)} onClick={()=>ask('nightAction',r.action==='guard'?'确认守护？':r.action==='seer'?'确认查验？':r.action==='witch'?'确认用药选择？':'确认狼队选择？',r.action==='witch'?(kind==='heal'?'使用解药救 '+label(r.victim):kind==='poison'?'毒 '+label(target):'本夜不用药'):'目标：'+label(target),{target:target||'pass',kind})}>{submitted?'修改本夜选择':'提交本夜行动'}</button>}
   {submitted&&<p className="success"><Check size={17}/>已提交，等待法官推进。</p>}
   {r.action==='wolves'&&Object.keys(r.wolfVotes).length>0&&<div className="team-votes">{Object.entries(r.wolfVotes).map(([pid,t])=><p key={pid}>{person(pid)?.seat} 号选择了 {label(t as string)}</p>)}</div>}
  </>}
  {r.phase==='night'&&!r.action&&<div className="wait-state"><Moon size={38}/><h3>{me?.alive?'天黑，请保持安静':'你已出局，安静观战'}</h3><p className="muted">轮到你时，操作会出现在这里。其他时间请不要在语音房透露信息。</p></div>}
  {r.phase==='speech'&&<><div className="speaker-clock"><Mic/><div><span>{speaker?.seat} 号 · {speaker?.name}</span><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b></div></div><p className="muted">{speaker?.id===me?.id?'现在是你的发言时间，说完请告诉法官。':'请听这位玩家发言，其他人先关闭麦克风。'}</p></>}
  {r.phase==='vote'&&<>{r.voteRound===2&&<p className="muted small">平票加投：先听平票玩家补充发言，再选择目标。</p>}<p className="muted small">已投 {r.voteCount} / {r.voteTotal} 票</p>{!r.canVote?<p className="muted">{me?.idiotRevealed?'你已翻牌，保留发言权，但不能再投票。':'你已出局，本轮无需投票。'}</p>:r.myVote?<p className="success"><Check size={17}/>已投给 {r.myVote==='pass'?'弃票':label(r.myVote)}，等待结果。</p>:<>{choice()}<button className="primary full" disabled={busy||!target} onClick={()=>ask('vote','确认投票？','提交后不能修改。'+(target==='pass'?'本轮弃票。':'你将投给 '+label(target)+'。'),{target})}>提交这一票</button></>}</>}
  {r.phase==='hunter'&&(r.hunter===me?.id?<><p className="muted">你可以带走一位存活玩家，也可以放弃开枪。</p>{choice()}<button className="primary full" disabled={busy||!target} onClick={()=>ask('shoot','确认猎人行动？',target==='pass'?'放弃本次开枪。':'带走 '+label(target),{target})}>确认猎人行动</button></>:<p className="muted">{label(r.hunter)} 正在决定是否开枪。</p>)}
  {r.phase==='dusk'&&<p className="muted">本轮已经结束，等待法官开始下一夜。</p>}
  {r.phase==='ended'&&<><p className="muted">所有身份已揭晓。等法官开启下一局，就能原座再战。</p><div className="result-mark"><Shield size={42}/><strong>{r.winner}获胜</strong></div></>}
  {me?.checks?.length>0&&<details className="private-checks"><summary>我的查验记录</summary>{me.checks.map((x:any)=><p key={x.day}>第 {x.day} 夜 · {x.seat} 号是{x.result}</p>)}</details>}
 </>}
 <div className="note"><Headphones size={16}/><span>网页处理流程，发言留在你们的语音房。</span></div></aside></div></main>:null}
 <footer><span>月下 · 好朋友的下一局</span><span>一起说话，认真说谎。</span></footer>
 <Dialog open={rules} onOpenChange={setRules}><DialogContent className="rules-dialog"><DialogHeader><DialogTitle>本桌玩法约定</DialogTitle><DialogDescription>6–12 位玩家，另加 1 位法官。本桌使用无警长流程。</DialogDescription></DialogHeader><div className="rules-content"><h3>本桌配置</h3><SetupSummary setup={currentSetup} size={r?.size||Number(size)}/><h3>链接入座，语音照常</h3><p>每人用自己的浏览器入座，法官不占玩家席位。配置确定后全部准备，再随机发牌。发牌前法官可以修改玩法，修改后全员重新准备。刷新可恢复席位，请不要清除浏览器数据。</p><h3>夜间行动</h3><p>{currentSetup.roles.guard?'顺序为守卫、狼人、预言家、女巫。':'顺序为狼人、预言家、女巫。'} 狼队唯一最高票生效，平票或全弃为空刀。预言家查验一名其他存活玩家。女巫每夜最多用一瓶药，解药用完后不再显示狼刀。{witchText(currentSetup)} 所有夜间死亡在天亮统一公布。</p>{currentSetup.roles.guard>0&&<><h3>守卫</h3><p>{ROLE_HELP.guard} 空守后下一夜可重新守之前的玩家。</p></>}{currentSetup.roles.idiot>0&&<><h3>白痴</h3><p>{ROLE_HELP.idiot}</p></>}<h3>发言与投票</h3><p>存活玩家按座位顺序发言，每人建议 90 秒。法官控制切换。投票不能投自己，可以弃票；平票玩家补充发言后加投一次，再平票则无人出局。除白痴翻牌外，死亡身份在终局统一揭晓。</p><h3>猎人与胜负</h3><p>猎人被刀或被放逐后可以开枪；中毒不能开枪。处理完猎人技能，再判断胜负。{victoryText(currentSetup)}</p><h3>法官的节奏</h3><p>阶段由法官推进，提前结束时未提交行动按放弃处理。已出局神职的夜间阶段也由法官走完，避免泄露身份。此版本采用无警长、无警徽、无自爆的主持流程，遗言由语音房约定。</p></div></DialogContent></Dialog>
 <Dialog open={identity} onOpenChange={setIdentity}><DialogContent className="identity-dialog"><DialogHeader><DialogTitle>你的身份 · {me?.seat} 号</DialogTitle><DialogDescription>只给你看，看完请收好。</DialogDescription></DialogHeader><div className={'identity-card '+(me?.role==='wolf'?'wolf':'')}><Shield size={46}/><h2>{ROLES[me?.role]||'尚未发放'}</h2><p>{ROLE_HELP[me?.role]}</p>{me?.role==='witch'&&<p className="small">{witchText(currentSetup)}</p>}{me?.role==='wolf'&&<p className="small">狼队：{r.wolfTeam.map((p:any)=>p.seat+' 号 '+p.name).join('、')}</p>}</div><button className="primary full" onClick={()=>{setIdentity(false);if(r.phase==='deal'&&!me?.ack)act('ack');}}>记住了，收好身份</button></DialogContent></Dialog>
 <Dialog open={!!editSetup} onOpenChange={open=>{if(!open)setEditSetup(null);}}><DialogContent className="rules-dialog"><DialogHeader><DialogTitle>修改本桌玩法</DialogTitle><DialogDescription>{r?.size} 人局 · 保存后全员需要重新准备</DialogDescription></DialogHeader>{editSetup&&<><SetupEditor size={r?.size} setup={editSetup} onChange={setEditSetup}/><button className="primary full" disabled={busy||!!configurationError(r?.size,editSetup)} onClick={()=>void send('configure',{setup:editSetup,epoch:editEpoch}).then(()=>setEditSetup(null)).catch(()=>{})}>保存玩法并重新准备</button></>}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.body}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>再想一下</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{if(confirm)act(confirm.action,{...confirm.args,epoch:confirm.epoch});setConfirm(null);}}>确认</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
